arb-dir: lib/presentation/localization/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppL10n
output-dir: lib/presentation/localization/gen
synthetic-package: false
nullable-getter: false
