import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

final GetIt getIt = GetIt.instance;

/// Wires the dependency graph. Generated by injectable into
/// `injection.config.dart` (run code generation after changing `@injectable`s).
@InjectableInit()
Future<void> configureDependencies() => getIt.init();
